### ISSUE TITLE
What's the current state of the lib?

### ISSUE THREAD

**Issue by svallory** [labXD/trpc-figma#4]
Hi, we tried to add this lib to a figma plugin but got a lot of issues trying to build the plugin after that. Starting with tRPC using `globalThis`, which  is not available in figma

**Comment by FlorentinoG9** [comment]
this only works if you install the monorepo and run the example directly, I cannot make it work by installing the dependency alone, and following instructions in my project, I might be missing something I got an error saying that the `./link` is not defined or something similar. is a cool project but I don't think this is being maintained.

**Comment by svallory** [comment]
@FlorentinoG9 take a look at https://figma-sdk.cva.design/?path=/docs/sdk-packages-rpc-beta--docs
